# Generated by Django 6.0.5 on 2026-06-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_providerprofile_rejection_reason'),
        ('services', '0006_provideravailability_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], default='instant', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], db_index=True, default='requested', max_length=20)),
                ('issue_description', models.TextField()),
                ('issue_photo', models.URLField(blank=True)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('customer_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_base_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('system', 'System')], max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.servicecategory')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_bookings', to='profiles.providerprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.providerservice')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_status_history',
                'ordering': ['timestamp'],
            },
        ),
    ]
