# Generated by Django 6.0.5 on 2026-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=20),
        ),
    ]
