# Generated by Django 6.0.5 on 2026-06-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='issue_photo',
            field=models.ImageField(blank=True, null=True, upload_to='booking_issues/'),
        ),
    ]
