# Generated by Django 6.0.5 on 2026-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('home', 'Home Services'), ('automotive', 'Automotive Services')], db_index=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('skill_tag', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'serice_categroies',
                'ordering': ['group', 'name'],
            },
        ),
    ]
