# Generated by Django 6.0.5 on 2026-05-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='skill_tag',
            new_name='skill_tags',
        ),
    ]
