# Generated by Django 6.0.5 on 2026-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_skill_tag_servicecategory_skill_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterModelTable(
            name='servicecategory',
            table='serice_categories',
        ),
    ]
