# Generated by Django 6.0.5 on 2026-05-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicecategory',
            table='service_categories',
        ),
    ]
