# Generated by Django 6.0.5 on 2026-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicecategory_skill_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
