# Generated by Django 6.0.5 on 2026-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_add_embedding_hnsw_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='semanticembedding',
            name='semantic_embedding_hnsw_idx',
        ),
        migrations.RenameField(
            model_name='semanticembedding',
            old_name='embedding',
            new_name='embeddng',
        ),
        migrations.AddIndex(
            model_name='semanticembedding',
            index=models.Index(fields=['content_type', 'object_id'], name='semantic_em_content_93fc20_idx'),
        ),
        migrations.RemoveField(
            model_name='semanticembedding',
            name='text',
        ),
    ]
