# Generated by Django 6.0.5 on 2026-06-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_remove_semanticembedding_semantic_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semanticembedding',
            old_name='embeddng',
            new_name='embedding',
        ),
    ]
