# Generated by Django 6.0.5 on 2026-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_rename_embeddng_semanticembedding_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticembedding',
            name='text',
            field=models.TextField(default=True),
        ),
    ]
