# Generated by Django 6.0.5 on 2026-06-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_requested', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('booking_on_the_way', 'Provider On The Way'), ('booking_arrived', 'Provider Arrived'), ('booking_in_progress', 'Work In Progress'), ('booking_completed', 'Booking Completed'), ('booking_disputed', 'Booking Disputed'), ('booking_auto_cancelled', 'Booking Auto Cancelled'), ('provider_approved', 'Provider Approved'), ('provider_rejected', 'Provider Rejected'), ('provider_suspended', 'Account Suspended'), ('provider_reactivated', 'Account Reactivated'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('booking_reminder', 'Booking Reminder'), ('service_verified', 'Service Verified'), ('service_rejected', 'Service Rejected'), ('payment_received', 'Payment Received'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected')], db_index=True, max_length=30),
        ),
    ]
