# Generated by Django 6.0.5 on 2026-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
