# Generated by Django 6.0.5 on 2026-06-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('profiles', '0005_providerprofile_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_locations', to='bookings.booking')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='profiles.providerprofile')),
            ],
            options={
                'db_table': 'provider_locations',
            },
        ),
    ]
