# Generated by Django 6.0.5 on 2026-05-21 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_photo', models.URLField(blank=True)),
                ('saved_addresses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_photo', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('service_radius_km', models.PositiveIntegerField(default=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_proof', 'ID Proof (Aadhaar / PAN / Passport)'), ('electrician_cert', 'Electrician ITI / Trade Certificate'), ('plumber_cert', 'Plumber ITI / Trade Certificate'), ('carpenter_cert', 'Carpenter Certificate'), ('painter_cert', 'Painter Certificate'), ('ac_cert', 'AC Technician Certificate'), ('appliance_cert', 'Appliance Repair Certificate'), ('cctv_cert', 'CCTV Installation Certificate'), ('pest_cert', 'Pest Control License'), ('driving_license', 'Driving License'), ('vehicle_rc', 'Vehicle RC Book'), ('mechanic_cert', 'Mechanic ITI Certificate'), ('towing_rc', 'Towing Vehicle RC'), ('work_photos', 'Previous Work Photos'), ('police_clearance', 'Police Clearance Certificate')], max_length=30)),
                ('file', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.providerprofile')),
            ],
            options={
                'db_table': 'provider_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
