# Generated by Django 6.0.5 on 2026-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerprofile',
            old_name='rating',
            new_name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
