# Generated by Django 6.0.5 on 2026-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_providerdocument_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
