# Generated by Django 6.0.5 on 2026-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_providerprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
