# Generated by Django 6.0.5 on 2026-06-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_providerprofile_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='upi_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='upi_verified',
            field=models.BooleanField(default=False),
        ),
    ]
