# Generated by Django 6.0.5 on 2026-06-20 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_providerprofile_upi_id_providerprofile_upi_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='upi_id',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='upi_name',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='upi_verified',
        ),
        migrations.AlterField(
            model_name='providerdocument',
            name='file',
            field=models.FileField(upload_to='provider_documents/'),
        ),
        migrations.CreateModel(
            name='ProviderBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('passbook_document', models.FileField(blank=True, null=True, upload_to='provider_bank/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='profiles.providerprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='ProviderKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='provider_kyc/pan/%Y/%m/')),
                ('pan_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pan_reject_reason', models.TextField(blank=True)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='provider_kyc/aadhaar/%Y/%m/')),
                ('aadhaar_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('aadhaar_reject_reason', models.TextField(blank=True)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='profiles.providerprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_kyc',
            },
        ),
    ]
