# Generated by Django 6.0.5 on 2026-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_providerprofile_upi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
