# Generated by Django 6.0.5 on 2026-06-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_customerprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
